### ISSUE TITLE
How to couple color temperature to screen brightness?

### ISSUE THREAD

**Issue by eMPee584** [Tookmund/setcolortemperature#2]
When using my laptop at home, I usually have the screen brightness high as long as I want to get something done, then turn it down (together with my room lighting) when I'm preparing to go to bed.
So (only!) in the evening, I would like to turn down color temp together with LCD brightness.
Any proposition how I could accomplish this?
nicer than comparing `/sys/class/backlight/thinkpad_screen/actual_brightness` with `max_brightness` in a cron script? ... :thinking: :thought_balloon:

**Comment by Tookmund** [comment]
Either ````xbacklight```` or ````xrandr --brightness```` called in a script along with ````sct```` should do the job.
Screen brightness is a mess on linux and screen-dependent in most cases. It's not something I think ````sct```` should do, but other tools exist to make it work.
